default_agent: clarityAgent
agents:
  clarityAgent:
    name: clarityAgent
    entrypoint: /Users/darren/CodeProjects/clarity/clarityAgent/agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/darren/CodeProjects/clarity/clarityAgent
    aws:
      execution_role: arn:aws:iam::278546699314:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-5f384f03ed
      execution_role_auto_create: false
      account: '278546699314'
      region: us-east-1
      ecr_repository: 278546699314.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-clarityagent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: clarityAgent-zi0ON6H3Bs
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:278546699314:runtime/clarityAgent-zi0ON6H3Bs
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-clarityagent-builder
      execution_role: arn:aws:iam::278546699314:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-5f384f03ed
      source_bucket: bedrock-agentcore-codebuild-sources-278546699314-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: clarityAgent_mem-OF91Z07w5Q
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:278546699314:memory/clarityAgent_mem-OF91Z07w5Q
      memory_name: clarityAgent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
